-- PBS_SERIAL_SAYIM_DETAIL tablosu oluşturma scripti
-- Bu tablo sayım detaylarını (seri numaralarını) saklar

CREATE TABLE PBS_SERIAL_SAYIM_DETAIL (
    SAYIM_ROW_ID INT IDENTITY(1,1) PRIMARY KEY,
    SAYIM_ID INT NULL,
    SERIAL_NUMBER NVARCHAR(150) NULL,
    IN_OUT BIT NULL DEFAULT 1
);

-- Foreign key constraint ekleme (isteğe bağlı)
-- ALTER TABLE PBS_SERIAL_SAYIM_DETAIL 
-- ADD CONSTRAINT FK_SAYIM_DETAIL_SAYIM 
-- FOREIGN KEY (SAYIM_ID) REFERENCES PBS_SERIAL_SAYIM(SAYIM_ID);

-- Index ekleme (performans için)
CREATE INDEX IX_PBS_SERIAL_SAYIM_DETAIL_SAYIM_ID ON PBS_SERIAL_SAYIM_DETAIL(SAYIM_ID);
CREATE INDEX IX_PBS_SERIAL_SAYIM_DETAIL_SERIAL ON PBS_SERIAL_SAYIM_DETAIL(SERIAL_NUMBER);

-- Örnek veri ekleme (test için)
/*
INSERT INTO PBS_SERIAL_SAYIM_DETAIL (SAYIM_ID, SERIAL_NUMBER, IN_OUT) VALUES
(1, 'SN001234567890', 1),
(1, 'SN001234567891', 1),
(1, 'SN001234567892', 0),
(2, 'SN001234567893', 1),
(2, 'SN001234567894', 1);
*/
