<cfquery name="trun" datasource="w3Qa_product">
TRUNCATE TABLE w3Qa_product.PRODUCT
TRUNCATE TABLE w3Qa_product.PRODUCT_UNIT_HISTORY
TRUNCATE TABLE w3Qa_product.PRODUCT_BRANCH
TRUNCATE TABLE w3Qa_product.PRODUCT_UNIT
TRUNCATE TABLE w3Qa_product.PRODUCT_COST
TRUNCATE TABLE w3Qa_product.PRODUCT_HISTORY
TRUNCATE TABLE w3Qa_product.PRODUCT_COST_LOG
TRUNCATE TABLE w3Qa_product.STOCKS
TRUNCATE TABLE w3Qa_product.PRICE_STANDART
TRUNCATE TABLE w3Qa_product.PRODUCT_GENERAL_PARAMETERS
TRUNCATE TABLE w3Qa_product.STOCKS_BARCODES
TRUNCATE TABLE w3Qa_product.PRODUCT_IMAGES
TRUNCATE TABLE w3Qa_product.PRODUCT_OUR_COMPANY
</cfquery>