       <cfquery name="getOfferStage" datasource="#DSN3#">
SELECT OFFER_ID,OFFER_STAGE,SUM(SS) SS FROM (
SELECT 
	DISTINCT
	ORR_SATIS_TEKLIFI.OFFER_ID,
	O_SATIS_TEKLIFI.OFFER_STAGE,
	(SELECT COUNT(*) FROM #dsn3#.ORDER_ROW WHERE WRK_ROW_RELATION_ID=ORR_SATIS_TEKLIFI.WRK_ROW_ID)	AS SS
FROM #dsn3#.OFFER_ROW AS ORR_SATIS_TEKLIFI
LEFT JOIN #dsn3#.OFFER_ROW AS ORR_ALIS_TEKLIFI ON ORR_ALIS_TEKLIFI.WRK_ROW_ID=ORR_SATIS_TEKLIFI.WRK_ROW_RELATION_ID
LEFT JOIN #dsn3#.OFFER AS O_ALIS_TEKLIFI ON O_ALIS_TEKLIFI.OFFER_ID=ORR_ALIS_TEKLIFI.OFFER_ID
LEFT JOIN #dsn3#.OFFER AS O_SATIS_TEKLIFI ON O_SATIS_TEKLIFI.OFFER_ID=ORR_SATIS_TEKLIFI.OFFER_ID
WHERE 
<cfif isDefined("attributes.last_offer_id") and LEN(attributes.last_offer_id)>
     ORR_SATIS_TEKLIFI.OFFER_ID = #attributes.last_offer_id#
   AND  </cfif> ORR_SATIS_TEKLIFI.WRK_ROW_RELATION_ID IN (
SELECT WRK_ROW_ID FROM #dsn3#.PBS_SELECTED_ROWS WHERE OFFER_ID=#attributes.internal_id#)
) AS T GROUP BY OFFER_ID,OFFER_STAGE

</cfquery>