/*
   PRODUCT_OEMS Tablosu Oluşturma Script'i
   
   Bu script, Excel'den veri aktarımı için gerekli PRODUCT_OEMS tablosunu oluşturur.
   Tablo 51 kolon içerir: ETA_KODU (zorunlu) + OEM_1'den OEM_50'ye kadar
*/

-- Eğer tablo varsa sil (isteğe bağlı - dikkatli kullanın!)
-- DROP TABLE IF EXISTS PRODUCT_OEMS;

-- PRODUCT_OEMS tablosunu oluştur
CREATE TABLE PRODUCT_OEMS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ETA_KODU NVARCHAR(255) NOT NULL,
    OEM_1 NVARCHAR(255) NULL,
    OEM_2 NVARCHAR(255) NULL,
    OEM_3 NVARCHAR(255) NULL,
    OEM_4 NVARCHAR(255) NULL,
    OEM_5 NVARCHAR(255) NULL,
    OEM_6 NVARCHAR(255) NULL,
    OEM_7 NVARCHAR(255) NULL,
    OEM_8 NVARCHAR(255) NULL,
    OEM_9 NVARCHAR(255) NULL,
    OEM_10 NVARCHAR(255) NULL,
    OEM_11 NVARCHAR(255) NULL,
    OEM_12 NVARCHAR(255) NULL,
    OEM_13 NVARCHAR(255) NULL,
    OEM_14 NVARCHAR(255) NULL,
    OEM_15 NVARCHAR(255) NULL,
    OEM_16 NVARCHAR(255) NULL,
    OEM_17 NVARCHAR(255) NULL,
    OEM_18 NVARCHAR(255) NULL,
    OEM_19 NVARCHAR(255) NULL,
    OEM_20 NVARCHAR(255) NULL,
    OEM_21 NVARCHAR(255) NULL,
    OEM_22 NVARCHAR(255) NULL,
    OEM_23 NVARCHAR(255) NULL,
    OEM_24 NVARCHAR(255) NULL,
    OEM_25 NVARCHAR(255) NULL,
    OEM_26 NVARCHAR(255) NULL,
    OEM_27 NVARCHAR(255) NULL,
    OEM_28 NVARCHAR(255) NULL,
    OEM_29 NVARCHAR(255) NULL,
    OEM_30 NVARCHAR(255) NULL,
    OEM_31 NVARCHAR(255) NULL,
    OEM_32 NVARCHAR(255) NULL,
    OEM_33 NVARCHAR(255) NULL,
    OEM_34 NVARCHAR(255) NULL,
    OEM_35 NVARCHAR(255) NULL,
    OEM_36 NVARCHAR(255) NULL,
    OEM_37 NVARCHAR(255) NULL,
    OEM_38 NVARCHAR(255) NULL,
    OEM_39 NVARCHAR(255) NULL,
    OEM_40 NVARCHAR(255) NULL,
    OEM_41 NVARCHAR(255) NULL,
    OEM_42 NVARCHAR(255) NULL,
    OEM_43 NVARCHAR(255) NULL,
    OEM_44 NVARCHAR(255) NULL,
    OEM_45 NVARCHAR(255) NULL,
    OEM_46 NVARCHAR(255) NULL,
    OEM_47 NVARCHAR(255) NULL,
    OEM_48 NVARCHAR(255) NULL,
    OEM_49 NVARCHAR(255) NULL,
    OEM_50 NVARCHAR(255) NULL,
    CREATED_DATE DATETIME DEFAULT GETDATE(),
    UPDATED_DATE DATETIME DEFAULT GETDATE()
);

-- ETA_KODU için index oluştur (performans için)
CREATE INDEX IX_PRODUCT_OEMS_ETA_KODU ON PRODUCT_OEMS(ETA_KODU);

-- Örnek veri ekleme (test için)
INSERT INTO PRODUCT_OEMS (ETA_KODU, OEM_1, OEM_2, OEM_3) 
VALUES 
('ETA001', 'OEM_VALUE_1', 'OEM_VALUE_2', 'OEM_VALUE_3'),
('ETA002', 'OEM_VALUE_4', 'OEM_VALUE_5', NULL),
('ETA003', 'OEM_VALUE_6', NULL, NULL);

-- Tablo yapısını kontrol et
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'PRODUCT_OEMS'
ORDER BY ORDINAL_POSITION;

-- Kayıt sayısını kontrol et
SELECT COUNT(*) AS TOTAL_RECORDS FROM PRODUCT_OEMS;

PRINT 'PRODUCT_OEMS tablosu başarıyla oluşturuldu!';
