CREATE TABLE USER_ACCESS_PBS (
  ACCESS_ID      INT IDENTITY(1,1) PRIMARY KEY,
  USER_ID        INT NOT NULL,
  ACCESS_TYPE    varchar(30) NOT NULL,   -- 'purchase','sales' vb.

);

CREATE TABLE USER_ACCESS_BRANDS_PBS (
  ACCESS_ID INT NOT NULL,
  BRAND_ID  INT NOT NULL
  
);

CREATE TABLE USER_ACCESS_COMPANIES_PBS (
  ACCESS_ID  INT NOT NULL,
  COMPANY_ID INT NOT NULL,
  
);