SELECT (
		SELECT DISTINCT ISNULL(SG.SERIAL_NO, S.BARCOD) SERIAL_NO
			,ISNULL(SG.STOCK_ID, S.STOCK_ID) STOCK_ID
			,S.PRODUCT_ID
			,CASE 
				WHEN ISNULL(SG.SERIAL_NO, '') = ''
					THEN SUM(AMOUNT)
				ELSE 1
				END AS AMOUNT
			,CASE 
				WHEN ISNULL(SG.SERIAL_NO, '') = ''
					THEN 0
				ELSE 1
				END AS IS_SERIAL
            ,(SELECT SUM(AMOUNT) FROM w3Qa_1.SHIPPING_PALLET_ROWS_PBS SPR WHERE SPR.PALLET_ID = 33 
            CASE 
				WHEN ISNULL(SG.SERIAL_NO, '') = ''
                    THEN AND STOCK_ID = S.STOCK_ID
                ELSE AND SERIAL_NO = ISNULL(SG.SERIAL_NO, S.BARCOD)
                END
            )
            
            AS TOTAL_AMOUNT
		FROM w3Qa_1.SHIPPING_PALLET_SVK_PBS SP
		LEFT JOIN w3Qa_1.EZGI_SHIP_RESULT ESR ON ESR.SHIP_RESULT_ID = SP.ORDER_ID
		LEFT JOIN (
			SELECT SF2026.FIS_ID
				,REF_NO
				,3 AS PERIODID
				,STOCK_ID
				,AMOUNT
			FROM w3Qa_2026_1.STOCK_FIS AS SF2026
			LEFT JOIN w3Qa_2026_1.STOCK_FIS_ROW AS SFR2026 ON SFR2026.FIS_ID = SF2026.FIS_ID
			
			UNION ALL
			
			SELECT SF2025.FIS_ID
				,REF_NO
				,2 AS PERIODID
				,STOCK_ID
				,AMOUNT
			FROM w3Qa_2025_1.STOCK_FIS AS SF2025
			LEFT JOIN w3Qa_2025_1.STOCK_FIS_ROW AS SFR2025 ON SFR2025.FIS_ID = SF2025.FIS_ID
			) SF ON SF.REF_NO = ESR.DELIVER_PAPER_NO
		LEFT JOIN w3Qa_1.SERVICE_GUARANTY_NEW SG ON SG.PROCESS_ID = SF.FIS_ID
			AND SG.PERIOD_ID = SF.PERIODID
		LEFT JOIN w3Qa_1.STOCKS S ON S.STOCK_ID = SF.STOCK_ID
        
		WHERE SP.PALLET_ID = 33
		GROUP BY SG.SERIAL_NO
			,S.BARCOD
			,SG.STOCK_ID
			,S.STOCK_ID
			,S.PRODUCT_ID
		FOR JSON PATH
		) AS T


    GO

SELECT * FROM SHIPPING_PALLET_ROWS_PBS WHERE PALLET_ID = 33 FOR JSON PATH





SELECT (
		SELECT DISTINCT ISNULL(SG.SERIAL_NO, S.BARCOD) AS SERIAL_NO
			,ISNULL(SG.STOCK_ID, S.STOCK_ID) AS STOCK_ID
			,S.PRODUCT_ID
			,CASE 
				WHEN ISNULL(SG.SERIAL_NO, '') = ''
					THEN SUM(AMOUNT)
				ELSE 1
				END AS AMOUNT
			,CASE 
				WHEN ISNULL(SG.SERIAL_NO, '') = ''
					THEN 0
				ELSE 1
				END AS IS_SERIAL
			,(
				SELECT SUM(SPR.AMOUNT)
				FROM w3Qa_1.SHIPPING_PALLET_ROWS_PBS AS SPR
				WHERE SPR.PALLET_ID =33
					AND (
						(
							ISNULL(SG.SERIAL_NO, '') = ''
							AND SPR.STOCK_ID = S.STOCK_ID
							)
						OR (
							ISNULL(SG.SERIAL_NO, '') <> ''
							AND SPR.SERIAL_NUMBER = ISNULL(SG.SERIAL_NO, S.BARCOD)
							)
						)
				) AS TOTAL_AMOUNT
		FROM w3Qa_1.SHIPPING_PALLET_SVK_PBS AS SP
		LEFT JOIN w3Qa_1.EZGI_SHIP_RESULT AS ESR ON ESR.SHIP_RESULT_ID = SP.ORDER_ID
		LEFT JOIN (
			SELECT SF2026.FIS_ID
				,REF_NO
				,3 AS PERIODID
				,STOCK_ID
				,AMOUNT
			FROM w3Qa_2026_1.STOCK_FIS AS SF2026
			LEFT JOIN w3Qa_2026_1.STOCK_FIS_ROW AS SFR2026 ON SFR2026.FIS_ID = SF2026.FIS_ID
			
			UNION ALL
			
			SELECT SF2025.FIS_ID
				,REF_NO
				,2 AS PERIODID
				,STOCK_ID
				,AMOUNT
			FROM w3Qa_2025_1.STOCK_FIS AS SF2025
			LEFT JOIN w3Qa_2025_1.STOCK_FIS_ROW AS SFR2025 ON SFR2025.FIS_ID = SF2025.FIS_ID
			) AS SF ON SF.REF_NO = ESR.DELIVER_PAPER_NO
		LEFT JOIN w3Qa_1.SERVICE_GUARANTY_NEW AS SG ON SG.PROCESS_ID = SF.FIS_ID
			AND SG.PERIOD_ID = SF.PERIODID
		LEFT JOIN w3Qa_1.STOCKS AS S ON S.STOCK_ID = SF.STOCK_ID
		WHERE SP.PALLET_ID = 33
		GROUP BY SG.SERIAL_NO
			,S.BARCOD
			,SG.STOCK_ID
			,S.STOCK_ID
			,S.PRODUCT_ID
		FOR JSON PATH
		) AS T;