----- seri no yaşam tablosu başlangıç değerlerini oluşturur ----
INSERT INTO w3Qa_1.SERIAL_IN_OUT_PBS(SERIAL_NUMBER,IS_ALIVE)
SELECT SERIAL_NO SERIAL_NUMBER,SUM(CASE WHEN IN_OUT =1 THEN 1 ELSE -1 END) AS IS_ALIVE FROM w3Qa_1.SERVICE_GUARANTY_NEW
GROUP BY 
SERIAL_NO


---- seri no yaşam tablosu başlangıç değerlerini günceller----
UPDATE SP
SET SP.STOCK_ID = SG.STOCK_ID
FROM w3Qa_1.SERIAL_IN_OUT_PBS SP
INNER JOIN w3Qa_1.SERVICE_GUARANTY_NEW SG
    ON SP.SERIAL_NUMBER = SG.SERIAL_NO
WHERE SG.IN_OUT = 1
  AND SG.IS_PURCHASE = 1


  SELECT * FROM w3Qa_1.SERIAL_IN_OUT_PBS
---- STOK FİŞİ HATASI----
  UPDATE w3Qa_2025_1.STOCK_FIS_ROW SET BASKET_EXTRA_INFO_ID =NULL

  ---ÜRÜN KARTI PAKET KONTROL TİPİ HATASI DÜXELTME----
  update w3Qa_product.PRODUCT SET PACKAGE_CONTROL_TYPE=1


  ----e-shipping sayfaları standrt ezgilerle çalkışınca ----

  DECLARE @FA NVARCHAR(MAX)=' sales.emptypopup_ajax_ezgi_shipping_detail'
DECLARE @W1_ID INT
DECLARE @W2_ID INT
select TOP 1 @W1_ID=WRK_OBJECTS_ID from w3Qa.WRK_OBJECTS where FULL_FUSEACTION=@FA AND MODULE_NO=2178
--PRINT @W1_ID
update w3Qa.WRK_OBJECTS set FULL_FUSEACTION=FULL_FUSEACTION+'_STD' where WRK_OBJECTS_ID=@W1_ID
select TOP 1 @W2_ID=WRK_OBJECTS_ID from w3Qa.WRK_OBJECTS where FULL_FUSEACTION=@FA 
update w3Qa.WRK_OBJECTS set MODULE_NO=1401 where WRK_OBJECTS_ID=@W2_ID



CREATE VIEW w3Qa_1.vw_SerialAliveWithDepo
AS
WITH SeriDepo AS (
  SELECT 
    SERIAL_NO,
    CAST(DEPARTMENT_ID AS NVARCHAR(10)) + '-' + CAST(LOCATION_ID AS NVARCHAR(10)) AS DEPO,
    SUM(CASE WHEN IN_OUT = 1 THEN 1 ELSE -1 END) AS NetAdet
  FROM w3Qa_1.SERVICE_GUARANTY_NEW
  GROUP BY SERIAL_NO, DEPARTMENT_ID, LOCATION_ID
  HAVING SUM(CASE WHEN IN_OUT = 1 THEN 1 ELSE -1 END) > 0
)
SELECT 
  SIOP.*,
  SD.DEPO
FROM w3Qa_1.SERIAL_IN_OUT_PBS SIOP
INNER JOIN SeriDepo SD ON SD.SERIAL_NO = SIOP.SERIAL_NUMBER
WHERE SIOP.IS_ALIVE = 1
 
